## docker-compose para correr wordpress con una base de datos en mysql
## by PeladoNerd https://youtu.be/eoFxMaeB9H4

version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    container_name: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuser@
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - /c/Users/Yoimer/Documents/development/wp:/var/www/html
    links:
      - mysql:mysql

  mysql:
    image: bitnami/mysql:latest
    restart: always
    container_name: wordpressdb
    ports:
      - 3306:3306
      # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: aqwe123
      MYSQL_PASSWORD: wpuser@
      MYSQL_USER: wpuser
    volumes:
      - //c/Users/Yoimer/MySQLData:/bitnami/mysql/data
      - //c/Users/Yoimer/MySQLConf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro