app:
  container_name: app
  restart: always
  build: .
  ports:
    - "4000:4000"
  links:
    - mongo
mongo:
  container_name: mongo
  image: mongo
  expose:
    - "27017"
  volumes:
  - /c/Users/Yoimer/Documents/development/docker-for-developers/backend/data:/data/db
  ports:
  - "27017:27017"